### ISSUE TITLE
Browser Compatibility

### ISSUE THREAD

**Issue by alan-boggess** [CIS-499-Group3/Team3-Project#2]
App doesn't work on Google Chrome 45.0.2454.101.

I'm not saying we should work on compatibility for the app, but I definitely think compatibility information is something we should include in the Readme.  I've updated it with the version of Firefox I have it working in and the version of Chrome it doesn't work in.  If anyone has another browser they're testing this in, please add that to the Readme.

(Do you guys think we should include the versions we can confirm it doesn't work in, or should we just include a list of supported browser versions?)

**Comment by alan-boggess** [comment]
P.s.:  Dr. Bethard uses Safari in class, right?  Does anybody have Safari to test it with?

**Comment by SpenceSellers** [comment]
I'll try to fix this. I think there's some weird dependency load order issue. Phaser absolutly SHOULD work on every platform. In the past it's run faster in chrome than in firefox, even.

**Comment by alan-boggess** [comment]
If you feel like tracking down dependency issues, be my guest, but I'd say this is low priority for now.  It's still just a prototype - it's OK if it only works on one platform.

**Comment by SpenceSellers** [comment]
Fixed it! 

Turned out to be kind of dumb. In game.ts I had it was waiting for "window.onload", which is usually a good think to do since you want everything else to be loaded by the time the game starts.

We're using require.js (which really simplifies this kind of thing a huge amount, that's how in the typescript we can just require() things instead of compiling them together into one huge file) BUT require.js also handles window.onload for you, so they weren't playing well together. Push incoming in a few seconds.
